CREATE TABLE JEDI
(
    FIRST_NAME VARCHAR(50) NOT NULL PRIMARY KEY,
    LAST_NAME  VARCHAR(50),
    FORCE_SIDE VARCHAR(50)
);

CREATE TABLE LIGHT_SABER
(
    OWNER       VARCHAR(50) NOT NULL PRIMARY KEY,
    COLOR       VARCHAR(50),
    DESCRIPTION VARCHAR(50),

    constraint FK_LIGHT_SABER_OWNER
        foreign key (OWNER) references JEDI (FIRST_NAME)
);
